# Welcome to Jekyll!

# Site settings
title: アジャイル四国 (Agile459)
email: agile459.info@gmail.com
description: 
  Agile459は、四国地域唯一のアジャイルな開発、アジャイルなビジネスを実践研究するためのコミュニティです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://agile459.github.io"
twitter_username: agile459
github_username:  agile459
language: ja

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md

header_pages:
  - about.md
  - 3reason.md
  - agile.md
  - join.md
  - archive.html
  - categories.html
  - tags.html